<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        let p1 = Promise.all([Promise.resolve("111"), Promise.resolve("222")])
        setTimeout(() => {
            console.log(p1)
        }, 0)
        p1.then((value) => { console.log(value) })

        // 有一个待定，返回的期约是待定
        let p2 = Promise.all([
            Promise.resolve(),
            new Promise(() => { })
        ])
        setTimeout(() => {
            console.log(p2)
        }, 0)


        // 有一个拒绝，返回的期约是拒绝
        let p3 = Promise.all([
            Promise.resolve(),
            Promise.reject("333"),
            new Promise((resolve, reject) => setTimeout(reject, 1000))
        ])
        setTimeout(() => {
            console.log(p3)
        }, 0)
        p3.then(null, (value) => { console.log(value) })

        let p4 = Promise.race([
            Promise.resolve("1111"),
            Promise.resolve("2222")
        ])
        setTimeout(() => { console.log(p4) }, 0)

        function runAsync(x) {
            const p = new Promise(resolve => setTimeout(() => resolve(x, console.log(x)), 1000))
            return p
        }
        function runReject(x) {
            const p = new Promise((res, rej) => setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x))
            return p
        }


        // Promise.all([runAsync(1), runAsync(2), runAsync(3)])
        //     .then(res => console.log(res))

        Promise.all([runAsync(1), runReject(4), runAsync(3), runReject(2)])
            .then(res => console.log(res,"dddd"))
            // 只有第一个error会被捕获
            .catch(err => console.log(err))

        // Promise.race([runAsync(1), runAsync(2), runAsync(3)])
        //     .then(res => console.log('result: ', res))
        //     .catch(err => console.log(err))



    </script>
</head>

<body>

</body>

</html>